name: CI Check

on: [push, pull_request]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./monitor

      - name: Lint code
        run: npm run lint
        working-directory: ./monitor

      - name: TypeScript check
        run: npm run type-check
        working-directory: ./monitor

      - name: Build project
        run: npm run build
        working-directory: ./monitor
